export const ru: Record<string, string> = {
    'yes': 'Да',
    'no': 'Нет',
    'body': 'Кузов',
    'brakes': 'Тормозная система',
    'light': 'Свет и поворотники',
    'motor': 'Двигатель',
    'interior': 'Интерьер',
    'transmission': 'Трансмиссия',
    'left': 'Слева',
    'right': 'Справа',
    'both': 'Слева и справа',
    'front': 'Впереди',
    'rear': 'Сзади',
    'plastic': 'Пластик',
    'metal': 'Метал',
    'many_materials': 'Много материалов',
    'i_do_not_know': 'Не знаю',
    'does_not_matter': 'Не важно / Неуместный вопрос',
}