/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('answers').del()
  await knex('answers').insert([
    {id: 1, text: 'Телевизор'},
    {id: 2, text: 'Чайник'},
    {id: 3, text: 'Сковорода'},
    {id: 4, text: 'Пылесос'},
    {id: 5, text: 'Утюг'},
    // {id: 6, text: 'Часы настенные'},
    // {id: 7, text: 'Тостер'},
    // {id: 8, text: 'Швабра'},
    // {id: 9, text: 'Ножницы'},
    // {id: 10, text: 'Плед'},
    // {id: 11, text: 'Вешалка для одежды'},
    // {id: 12, text: 'Зубная щетка'},
    // {id: 13, text: 'Фен для волос'},
    // {id: 14, text: 'Блендер'},
    // {id: 15, text: 'Гладильная доска'},
    // {id: 16, text: 'Тарелки'},
    // {id: 17, text: 'Стаканы'},
    // {id: 18, text: 'Ложки, вилки, ножи'},
    // {id: 19, text: 'Ваза'},
    // {id: 20, text: 'Лампа настольная'},
    // {id: 21, text: 'Термометр'},
    // {id: 22, text: 'Зеркало'},
    // {id: 23, text: 'Ведро для мусора'},
    // {id: 24, text: 'Подушка'},
    // {id: 25, text: 'Простыни'},
    // {id: 26, text: 'Полотенце'},
    // {id: 27, text: 'Кастрюля'},
    // {id: 28, text: 'Микроволновая печь'},
    // {id: 29, text: 'Кофемолка'},
    // {id: 30, text: 'Корзина для белья'},
    // {id: 31, text: 'Чайный сервиз'},
  ]);

  await knex('questions').del()
  await knex('questions').insert([
    
    {id: 1, text: 'Что вы ищите тяжелое?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 2, text: 'Что вы ищите весит на стене?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 3, text: 'Что вы ищите стоит на тумбе?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 4, text: 'Что вы ищите показывает фильмы?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 5, text: 'Что вы ищите подключено к интернету?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 6, text: 'Что вы ищите кипятит воду?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 7, text: 'Что вы ищите включается в розетку?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 8, text: 'Что вы ищите помогает приготовить чай?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 9, text: 'Что вы ищите используется для приготовления пищи?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 10, text: 'Что вы ищите нагревается на плите?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 11, text: 'Что вы ищите может помочь с котлетами?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 12, text: 'Что вы ищите наводит уборку?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 13, text: 'Что вы ищите всасывает в себя?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 14, text: 'Что вы ищите имеет емкость для сбора мусора?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 15, text: 'Что вы ищите сильно нагревается?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 16, text: 'Что вы ищите помогает гладить одежду?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    {id: 17, text: 'Что вы ищите имеет воду внутри?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 1, text: 'Что вы ищите тяжелое?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 2, text: 'Что вы ищите, чтобы вскипятить воду?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 3, text: 'Что вы ищите для жарки продуктов?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 4, text: 'Что вы ищите, чтобы убрать пыль с пола?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 5, text: 'Что вы ищите для разглаживания складок на одежде?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 6, text: 'Что вы ищите, чтобы узнать время, вися на стене?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 7, text: 'Что вы ищите для поджаривания хлеба?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 8, text: 'Что вы ищите для мытья полов?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 9, text: 'Что вы ищите для разрезания бумаги?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 10, text: 'Что вы ищите для уюта в холодные вечера?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 11, text: 'Что вы ищите, чтобы повесить одежду?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 12, text: 'Что вы ищите для очистки зубов?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 13, text: 'Что вы ищите для сушки волос?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 14, text: 'Что вы ищите для измельчения продуктов?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 15, text: 'Что вы ищите для удобства глажки?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 16, text: 'Что вы ищите, чтобы на них класть еду?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 17, text: 'Что вы ищите для питья чая или воды?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 18, text: 'Что вы ищите для еды супа или разрезания еды?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 19, text: 'Что вы ищите для украшения комнаты цветами?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 20, text: 'Что вы ищите для освещения стола?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 21, text: 'Что вы ищите, чтобы узнать температуру в комнате?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 22, text: 'Что вы ищите, чтобы увидеть свое отражение?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 23, text: 'Что вы ищите для выбрасывания мусора?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 24, text: 'Что вы ищите для комфортного сна?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 25, text: 'Что вы ищите, чтобы накрыть кровать?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 26, text: 'Что вы ищите для вытирания рук или тела после душа?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 27, text: 'Что вы ищите для варки блюд?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 28, text: 'Что вы ищите для разогрева еды?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 29, text: 'Что вы ищите для измельчения кофейных зерен?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 30, text: 'Что вы ищите для хранения грязного белья?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
    // {id: 31, text: 'Что вы ищите для сервировки чая?', hidden_from_ui: false, shown_only_for_doctors: false, possibility_of_this_is_next: 0.0},
  ]);
};
